[settings]
    class = "Chain"
    contained_by = "status"
    doc_group = "04-Admin"
    doc_descr = "a configuration item carrying information about a single chain"
    doc_route = "439-chain"
    produced_by = "status, config"
