[settings]
class = CChunkRecord
fields = chunkrecord.csv
doc_group = 04-Admin
doc_descr = a single record in the manifest detailing the IPFS hases and file sizes for each bloom filter and index chunk
doc_route = 403-chunkRecord
doc_producer = chunks, init, scrape
go_output = src/apps/chifra/pkg/types
