[settings]
class = CManifest
fields = manifest.csv
doc_group = 04-Admin
doc_descr = a JSON object containing records for each bloom filter and index chunk in the Unchained Index
doc_route = 402-manifest
doc_producer = chunks, init, scrape
go_output = src/apps/chifra/pkg/types
