[settings]
    class = "Parameter"
    contained_by = "function, parameter"
    doc_group = "05-Other"
    doc_descr = "an input or output parameter to a Solidity function or event"
    doc_route = "509-parameter"
    attributes = ""
    produced_by = "abis, export, transactions, receipts, logs, traces, state, slurp"
    contains = "parameter"
    cache_type = "marshal_only"
