[settings]
    class = "Statement"
    contained_by = "transaction"
    doc_group = "01-Accounts"
    doc_descr = "a statement, including all inflows and outflows, for a single transfer of an asset (including ETH) to or from a given address"
    doc_route = "118-statement"
    produced_by = "export"
    cache_type = "cacheable"
    cache_by = "address,tx"
    cache_as = "group"
