[settings]
    class = "State"
    doc_group = "03-Chain State"
    doc_descr = "the state of an Ethereum account (EOA or smart contract) on-chain"
    doc_route = "303-state"
    produced_by = "state"
    cache_type = "cacheable"
    cache_by = "address,block"
