[settings]
class = CWithdrawal
fields = withdrawal.csv
doc_group = 02-Chain Data
doc_descr = withdrawal record for post-Shanghai withdrawals from the consensus layer
doc_route = 204-withdrawal
doc_producer = blocks
go_output = src/apps/chifra/pkg/types
cache_type = cacheable
cache_by = block
cache_as = group
