[settings]
    class = "CWithdrawal"
    contained_by = "block"
    doc_group = "02-Chain Data"
    doc_descr = "withdrawal record for post-Shanghai withdrawals from the consensus layer"
    doc_route = "209-withdrawal"
    produced_by = "blocks"
    cache_type = "cacheable"
    cache_by = "block"
    cache_as = "group"
