version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: unused-parameter
          severity: warning
    staticcheck:
      checks:
        - all
        - -QF1008 # could remove embedded field "Xxx" from selector
        - -QF1006 # could lift into loop condition
        - -ST1003 # should not use MixedCaps in package name
        - -ST1016 # methods on the same type should have the same receiver name
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
        path: src/apps/chifra/internal/scrape/handle_show.go
      - linters:
          - ineffassign
        path: src/apps/chifra/internal/[^/]+/options\.go
      - linters:
          - ineffassign
        path: src/apps/chifra/pkg/types/types_
      - linters:
          - errcheck
          - goconst
          - gosec
          - ineffassign
          - misspell
          - prealloc
          - revive
          - staticcheck
          - unused
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go
