before:
  hooks:
    - go mod tidy

builds:
  - dir: cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

release:
  prerelease: "true" # Correctly marked as a pre-release
