version: 2
builds:
  - dir: src/apps/chifra
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
release:
  prerelease: "false"
  draft: false
  github:
    owner: trueblocks
    name: trueblocks-core
  name_template: "{{ .Tag }} - {{ .TagSubject }}"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^Merge"
      - "^merge"
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
