before:
  hooks:
    - go mod tidy

builds:
  - dir: cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

release:
  draft: true # Create releases as drafts to avoid cluttering public release history
  prerelease: true # Mark the releases as pre-releases (useful for distinguishing test releases)

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
