all:
	@echo ; colorEcho -t "Building apps..."
	@cd blockScraper ; make
	@cd chifra ; make
	@cd ethprice ; make
	@cd ethslurp ; make
	@cd grabABI ; make
	@cd makeClass ; make
	@cd miniBlocks ; make

test:
	@cd blockScraper ; make test
	@cd chifra ; make test
	@cd ethprice ; make test
	@cd ethslurp ; make test
	@cd grabABI ; make test
	@cd makeClass ; make test
	@cd miniBlocks ; make test

testall:
	@cd blockScraper ; make testall
	@cd chifra ; make testall
	@cd ethprice ; make testall
	@cd ethslurp ; make testall
	@cd grabABI ; make testall
	@cd makeClass ; make testall
	@cd miniBlocks ; make testall

clean:
	@cd blockScraper ; make clean
	@cd chifra ; make clean
	@cd ethprice ; make clean
	@cd ethslurp ; make clean
	@cd grabABI ; make clean
	@cd makeClass ; make clean
	@cd miniBlocks ; make clean
