#!/usr/bin/python

import sys
import subprocess
import os
import time
import signal

# Signals handler, to deal with Ctrl+C stuff
def signal_handler(signal, frame):
    print('You pressed Ctrl+C!')
    sys.exit(0)

# Define a signals handler to capture at least Ctrl+C
signal.signal(signal.SIGINT, signal_handler)

os.chdir('../monitors')
os.system('ls | grep -v scripts | grep -v README | sort -uf >/tmp/junk')
#while True:
with open('/tmp/junk') as f:
    os.system('clear')
#    contracts = f.read().splitlines()
#    contracts = [ 'ENS', 'augur', 'binance', 'bnt', 'dao', 'firstBlood', 'gnosis', 'quantstamp', 'singular', 'tenX', 'tierion', 'walton', 'forRichard' ]
    contracts = [ 'accts', 'addressHandle', 'customer_1', 'eSports', 'etherTip', 'expertyHack', 'firstAcct', 'fyn', 'giveth_ff', 'maker', 'paritySMS', 'rchain', 'uportClaims', 'whiteHat', 'uportClaims' ]
    for contract in contracts:
        command = 'cd ' + contract + ' ; cacheMan --cacheBals cache/0x*.acct.bin ; cd - >/dev/null'
        print(command)
        os.system(command)
    f.close()
os.system('clearLocks')
