all:
	@cd colorTest ; make
	@cd exportContext ; make
	@cd jsonTest ; make
	@cd stringTest ; make
	@cd tomlTest ; make

testall:
test:
	@make
	@cd colorTest ; make test
	@cd exportContext ; make test
	@cd jsonTest ; make test
	@cd stringTest ; make test
	@cd tomlTest ; make test

clean:
	@cd colorTest ; make clean
	@cd exportContext ; make clean
	@cd jsonTest ; make clean
	@cd stringTest ; make clean
	@cd tomlTest ; make clean
