#!/usr/bin/env bash

echo "Running by date with $1"
bin/issuance --by_date $1 >data/by_$1.csv
echo "Running by date with $1 --ether"
bin/issuance --by_date $1 --ether >data/by_$1_ether.csv
echo "Running by date with $1 --ether --discrete"
bin/issuance --by_date $1 --ether --discrete >data/by_$1_ether_discrete.csv
