openapi: 3.1.3
info:
  title: TrueBlocks API
  contact:
    email: info@trueblocks.io
    url: https://www.trueblocks.io
  license:
    name: GPL 3.0
    url: http://www.gnu.org/licenses/
  version: 2.5.8-release
  description: >
[{DESCRIPTION}]servers:
  - url: http://localhost:8080
    description: Local endpoints
tags:
  - name: Accounts
    description: Access and cache transactional data
  - name: Chain Data
    description: Access and cache blockchain-related data
  - name: Chain State
    description: Access to account and token state
  - name: Admin
    description: Control the scraper and build the index
  - name: Other
    description: Access to other and external data
paths:
[{PATHS}][{COMPONENTS}]
