all:
	@cd abilib ; make
	@cd acctlib ; make
	@cd etherlib ; make
	@cd utillib ; make

test:
	@cd abilib ; make test
	@cd acctlib ; make test
	@cd etherlib ; make test
	@cd utillib ; make test

testall:
	@cd abilib ; make testall
	@cd acctlib ; make testall
	@cd etherlib ; make testall
	@cd utillib ; make testall

clean:
	@cd abilib ; make clean
	@cd acctlib ; make clean
	@cd etherlib ; make clean
	@cd utillib ; make clean
