#!/usr/bin/env bash

make ; clear

echo ; colorEcho -t "Testing infura"
time bin/bloomScan infura 300000 301000 1

echo ; colorEcho -t "Testing local node"
time bin/bloomScan local  300000 301000 1

echo ; colorEcho -t "Testing quickBlocks"
time bin/bloomScan binary 300000 301000 1
