#!/usr/bin/env bash

defTag="81 Other"
defSource="Etherscan"
defDecimals=""

export TB_NAME_ADDRESS=$1
export TB_NAME_NAME=$2
export TB_NAME_TAG=${3:-$defTag}
export TB_NAME_SOURCE=${4:-$defSource}
export TB_NAME_SYMBOL=$5
export TB_NAME_DECIMALS=${6:-$defDecimals}
export TB_NAME_DESCR=$7
export TB_NAME_CUSTOM=false

chifra names --create >/dev/null
cp -pf /Users/jrush/.quickBlocks/names/names.tab /Users/jrush/Development/trueblocks-core/src/other/install/names/names.tab
chifra names --all --expand $1
