#!/usr/bin/env bash

cd ..
export QUICKBLOCKS=`pwd`

cd $QUICKBLOCKS/build/
cmake ../src

cd $QUICKBLOCKS/build/$1
make
#make test-all | tee test_all_results
doTestingApi --filter all --which both --err_quit

cat test_all_results | cut -c6-1000 | grep "^-" | cut -c2-1000 | sed 's/ (Failed)//' | sed 's/^/diffTest/' >x
mv -f x test_all_results
chmod uog+x test_all_results

cd $QUICKBLOCKS/test/
echo "Removing compare folder..."
rm -fR compare/

echo "Copying working to compare..."
cp -pR working compare
find compare -name "*gitignore*" -exec rm '{}' ';'
rm -fR gold/apps/acctScrape/99_1234...7890
cd $QUICKBLOCKS/build/

echo "Done..."
