#!/usr/bin/env bash

# echo $DOCKER_FOLDER
if [ -d ${DOCKER_FOLDER} ]; then
    cd $DOCKER_FOLDER
    touch api/testing
    touch api/server.js
fi

# echo "Testing..."
cd $TEST_FOLDER/gold/dev_tools/testRunner

testRunner $@ | tee $BUILD_FOLDER/results.txt

cat $BUILD_FOLDER/results.txt | grep -v Skipping >x
mv -f x $BUILD_FOLDER/results.txt

#echo "Reseting docker repo..."
if [ -d ${DOCKER_FOLDER} ]; then
    cd $DOCKER_FOLDER
    rm -f api/testing
    touch api/server.js
fi

cd $BUILD_FOLDER
