#!/usr/bin/env bash

cd ..
export QUICKBLOCKS=`pwd`
export BUILD_FOLDER=$QUICKBLOCKS/build/
export TEST_FOLDER=$QUICKBLOCKS/test/
export DOCKER_FOLDER=$QUICKBLOCKS/../trueblocks-docker/

echo "Making..."
cd $BUILD_FOLDER/
cmake ../src
make

echo "Testing..."
cd $BUILD_FOLDER/$1
#make test-all | tee test_all_results
cat test_results | cut -c6-1000 | grep "^-" | cut -c2-1000 | sed 's/ (Failed)//' | sed 's/^/diffTest/' >x
mv -f x test_results
chmod uog+x test_results

echo "Testing 2..."
cd $BUILD_FOLDER/
echo "Calling : doTestingApi $@ --filter all  --which both"
doTestingApi $@ --filter all --which both
# --err_quit

echo "Copying working folder to compare folder..."
cd $TEST_FOLDER/
rm -fR compare/
cp -pR working compare
find compare -name "*gitignore*" -exec rm '{}' ';'
rm -fR gold/apps/acctScrape/99_1234...7890

cd $BUILD_FOLDER
echo "Done..."
