#!/usr/bin/env bash

cd ..
export QUICKBLOCKS=`pwd`
export BUILD_FOLDER=$QUICKBLOCKS/build/
export TEST_FOLDER=$QUICKBLOCKS/test/
export DOCKER_FOLDER=$QUICKBLOCKS/../trueblocks-explorer/

#echo "Making..."
cd $BUILD_FOLDER/
cmake ../src
make generate finish
make -j 8

doTestingApi --filter all --mode both --clean --report $@

cd $BUILD_FOLDER
echo "Done..."
