#!/usr/bin/env bash

cd ..
export QUICKBLOCKS=`pwd`
export BUILD_FOLDER=$QUICKBLOCKS/build/
export TEST_FOLDER=$QUICKBLOCKS/test/
export DOCKER_FOLDER=$QUICKBLOCKS/../trueblocks-explorer/

#echo "Making..."
cd $BUILD_FOLDER/
cmake ../src
cd dev_tools
make -j 8
cd ..
make -j 8
doTestingApi --filter fast --mode cmd --no_quit $@

cd $BUILD_FOLDER
echo "Done..."
