#!/usr/bin/env bash

defTag="81 Other"
defSource="Etherscan"
defDecimals=""

ADDRESS=$1
NAME=$2
TAG=${3:-$defTag}
SOURCE=${4:-$defSource}
SYMBOL=$5
DECIMALS=${6:-$defDecimals}
DESCR=$7

echo "---------------------- Adding -----------------------"
echo "Address: " $ADDRESS
echo "Name: " $NAME
echo "TAG: " $TAG
echo "SOURCE: " $SOURCE
echo "DECIMALS: " $DECIMALS
echo "SYMBOL: " $SYMBOL
echo "DESCR: " $DESCR

# tags\taddress\tname\tsymbol\tsource\tdescription\tdecimals\tdeleted\tis_custom\tis_prefund
chifra names --editCmd update "$TAG!$ADDRESS!$NAME!$SYMBOL!$SOURCE!$DESCR!$DECIMALS" >/dev/null
cp -pf /Users/jrush/.quickBlocks/names/names.tab /Users/jrush/Development/trueblocks-core/src/other/install/names/names.tab
chifra names --expand --all $1
