#!/usr/bin/env bash
#
# Usage: grepAll search_term grep_params
#
# Searches through source code files of entire code tree
# for 'search_term'. Prints results to screen
#
if [ "$(uname)" == "Darwin" ]; then
    find -E . -iregex ".*\.(h|cpp|toml|ake|md|py|js|jsx|sql|csv|go|css)" -exec grep -Hs$2 "$1" '{}' ';' | grep -v ^Binary
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    find . -regextype posix-extended -iregex ".*\.(h|cpp|toml|ake|md|py|js|jsx|sql|csv|go|css)" -exec grep -Hs$2 "$1" '{}' ';' | grep -v ^Binary
fi
