#!/usr/bin/env bash
#
# Usage: lintAll <optional_param_to_pylint>
#
# Lints all .cpp or .h files found in this folder or any children folders
#
find . -name "*.[ch]*" -exec clang-format --verbose -i '{}' ';' 2>&1 | sed 's/cpp$/ccp|/' | sed 's/h$/h|/' | tr '|' '\r'
