#!/usr/bin/env python

import sys, getopt

def main(argv):
   color1 = ''
   color = '\033[92m'
   text = ''
   try:
      opts, args = getopt.getopt(argv,"hc:t:",["color=","text="])
   except getopt.GetoptError:
      print ('colorEcho.py -c <color> -t <text>')
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-h':
         print ('colorEcho.py -c <color> -t <text>')
         sys.exit()
      elif opt in ("-c", "--color"):
         color1 = arg
         if arg in ("GRAY", "gray"):
            color = '\033[90m'
         elif arg in ("RED", "red"):
            color = '\033[91m'
         elif arg in ("GREEN", "green"):
            color = '\033[92m'
         elif arg in ("YELLOW", "yellow"):
            color = '\033[93m'
         elif arg in ("BLUE", "blue"):
            color = '\033[94m'
         elif arg in ("MAGENTA", "magenta"):
            color = '\033[95m'
         elif arg in ("TEAL", "teal"):
            color = '\033[96m'
         elif arg in ("WHITE", "white"):
            color = '\033[97m'
         else:
            color = '\033[97m'
      elif opt in ("-t", "--text"):
         text = arg
#   print 'Color is ' + color1
#   print 'Text is ' + text
   print (color + '\033[1m' + text + '\033[0m')

if __name__ == "__main__":
   main(sys.argv[1:])

#print 'Number of arguments:', len(sys.argv), 'arguments.'
#print 'Argument List:', str(sys.argv)
#print bcolors.GRAY + "Gray" + bcolors.ENDC
#print bcolors.RED + "Red" + bcolors.ENDC
#print bcolors.GREEN + "Green" + bcolors.ENDC
#print bcolors.YELLOW + "Yellow" + bcolors.ENDC
#print bcolors.BLUE + "Blue" + bcolors.ENDC
#print bcolors.MAGENTA + "Magenta" + bcolors.ENDC
#print bcolors.TEAL + "Teal" + bcolors.ENDC
#print bcolors.WHITE + "White" + bcolors.ENDC
#print bcolors.BOLD + "Bold" + bcolors.ENDC
#print bcolors.ITALIC + "Italic" + bcolors.ENDC
#print bcolors.UNDERLINE + "Underline" + bcolors.ENDC
