all:
	@echo ; colorEcho -t "Building tools..."
	@cd ethName ; make
	@cd getBalance ; make
	@cd getBlock ; make
	@cd getLogs ; make
	@cd getReceipt ; make
	@cd getTrace ; make
	@cd getTrans ; make
	@cd isContract ; make
	@cd whenBlock ; make

test:
	@cd ethName ; make test
	@cd getBalance ; make test
	@cd getBlock ; make test
	@cd getLogs ; make test
	@cd getReceipt ; make test
	@cd getTrace ; make test
	@cd getTrans ; make test
	@cd isContract ; make test
	@cd whenBlock ; make test

testall:
	@cd ethName ; make testall
	@cd getBalance ; make testall
	@cd getBlock ; make testall
	@cd getLogs ; make testall
	@cd getReceipt ; make testall
	@cd getTrace ; make testall
	@cd getTrans ; make testall
	@cd isContract ; make testall
	@cd whenBlock ; make testall

clean:
	@cd ethName ; make clean
	@cd getBalance ; make clean
	@cd getBlock ; make clean
	@cd getLogs ; make clean
	@cd getReceipt ; make clean
	@cd getTrace ; make clean
	@cd getTrans ; make clean
	@cd isContract ; make clean
	@cd whenBlock ; make clean
