#!/usr/bin/env bash

# set parameters and defaults
if [ $# -lt 1 ]; then
    echo "Using default port 8545, if you want to use a specific port, pass it as the first argument"
    PORT=8545
else
    echo "Using port $1"
    PORT=$1
fi
if [ $# -lt 2 ]; then
    echo "Using default output directory of ""produced"", if you want to use a specific output directory, pass it as the second parameter"
    output_dir="produced"
else
    output_dir=$2
fi
export RPC_ENDPOINT="http://localhost:$PORT"

# make and clean output folder
mkdir -p "$output_dir"
rm -f "$output_dir"/*

tests=("trace_call_all" "trace_call_none" "trace_call_trace" "trace_call_vmTrace" "trace_call_stateDiff" "trace_call_view" "trace_call_view_none" "trace_call_error" "trace_callMany_all" "trace_callMany_none" "trace_callMany_trace" "trace_callMany_vmTrace" "trace_callMany_stateDiff" "trace_replayTransaction_all" "trace_replayTransaction_none" "trace_replayTransaction_trace" "trace_replayTransaction_vmTrace" "trace_replayTransaction_stateDiff" "trace_replayBlockTransactions_all" "trace_replayBlockTransactions_none" "trace_replayBlockTransactions_trace" "trace_replayBlockTransactions_vmTrace" "trace_replayBlockTransactions_stateDiff" "trace_rawTransaction_none" "trace_rawTransaction_trace" "trace_rawTransaction_vmTrace" "trace_get_0" "trace_get_3" "trace_get_5" "trace_get_10" "trace_transaction" "trace_block" "trace_filter")

for test in "${tests[@]}"
do
    ./run_test $test $output_dir
done

# why are we not running these?
#./run_test trace_rawTransaction_all
#./run_test trace_rawTransaction_stateDiff
