#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "You must specify the rest to run as the first parameter"
else
    echo "Running test: $1"
fi

if [ $# -lt 2 ]; then
    echo "Using default output directory of ""produced"", if you want to use a specific output directory, pass it as the second parameter"
    output_dir="produced"
else
    output_dir=$2
fi

echo "Running test: $1"
source tests/$1.json $RPC_ENDPOINT | jq -S >$output_dir/$1.json
