#!/usr/bin/env bash

rm -fR objs
rm -fR parselib/objs
rm -f parselib/* 2>&1 | grep -v "is a directory"
rm -f parselib/classDefinitions/* 2>&1 | grep -v "is a directory"
rm -f cache/*
rm -f tests/*

echo s/$1/$2/g >shit

mv ./proj.xcodeproj/xcuserdata/jrush.xcuserdatad/xcschemes/$1.xcscheme ./proj.xcodeproj/xcuserdata/jrush.xcuserdatad/xcschemes/$2.xcscheme

fixProj.1 ./proj.xcodeproj/project.pbxproj
fixProj.1 ./proj.xcodeproj/project.xcworkspace/contents.xcworkspacedata
fixProj.1 ./proj.xcodeproj/xcuserdata/jrush.xcuserdatad/xcschemes/xcschememanagement.plist
fixProj.1 ./proj.xcodeproj/xcuserdata/jrush.xcuserdatad/xcschemes/$2.xcscheme

rm -f shit
rm -f bin/accounting

echo
echo "Project updated"
echo
echo "You need to edit the ./rebuild script, the config.toml file, and the makefile"
