package main

/*
 * TrueBlocks API
 *
 * An API for accessing cached Ethereum blockchain data and accounts
 *
 * API version: 0.8.04
 * Contact: jrush@quickblocks.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

import (
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	tb "./cmd"
)

func main() {
	if os.Getenv("TEST_MODE") == "true" || tb.FileExists("/tmp/test-api") {
		log.Print("Running in testing mode")
	}
	port := "8080"
	log.Printf("Server started at port " + port)
	router := tb.NewRouter()
	log.Fatal(http.ListenAndServe(":"+port, router))
}
