#!/usr/bin/env bash

rm -f results
rm -fR one two
mkdir -p one two

BLOCKS1="15000000-15000300"
BLOCKS2="2010010 3010010"
TRANS1="15000000.*"
TRANS2="1001001.*"
TRANS3="2000000-3000000:1000"

./test_cache.1 blocks         $BLOCKS1 --hashes             | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 blocks         $BLOCKS2                      | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 blocks         $BLOCKS1 --hashes --cache_txs | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 blocks         $BLOCKS2 --cache_txs          | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 blocks         $BLOCKS2 --raw                | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results

#./test_cache.1 transactions  15000000.\* | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* --raw | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* --articulate | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* --uniq | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* "--uniq --flow from" | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* "--logs" | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* "--logs --topic 0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31" | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
#./test_cache.1 transactions  15000000.\* "--logs --emitter 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results

./test_cache.1 receipts      $TRANS1              | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 receipts      $TRANS1 --raw        | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 receipts      $TRANS1 --articulate | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results

./test_cache.1 logs          $TRANS1              | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 logs          $TRANS1 --raw        | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
./test_cache.1 logs          $TRANS1 --articulate | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results

#./test_cache.1 traces       $TRANS2              | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results

./test_cache.1 when          $TRANS3              | sed 's/INFO/|INFO/' | tr '|' '\n' | grep INFO | tee -a results
