#!/usr/bin/env bash
#
# slurp_using_ethslurp
#
#   Use 'ethslurp' to read EtherScan list of transactions per account. Export the
#   result to the file we will use to comapre against qblocks related lists
#
#   slurp_using_ethslurp <address> <name> <optional_folder>
#
#   where
#       <address> is the address of the account you wish to scrape
#       <name>    is the user assigned name for the contract (such as token symbol for example)
#       <folder>  is an optional folder in which which is pre-pended to filename
#
#--
# Make input params easier to see
#
address=$1
filename=$3$2-$1

#--
# Default block range
#
start=0
stop=6250000

#--
# For this code to work, you must add these entries to your ~/.quickblocks/ethslurp.toml file
#
#   [display]
#   fmt_ethscan_fieldList = blockNumber|transactionIndex|hash
#   fmt_ethscan_file      = [{HEADER}]\n[{RECORDS}]
#   fmt_ethscan_record    = [{FIELDS}]\n
#   fmt_ethscan_field     = \t[{FIELD}]
#

#--
# The files we want to create
#
es_result=txt/$filename.txt
es_ext_results=results/$filename-ext.txt
es_int_results=results/$filename-int.txt
es_both_results=results/$filename-both.txt

#--
# Export regular transactions to a temporary file
#
ethslurp $address --type ext --blocks $start-$stop --fmt:ethscan >$es_ext_results

#--
# Export internal transactions
#
ethslurp $address --type int --blocks $start-$stop --fmt:ethscan >$es_int_results

#--
# Put the files together (keeping only real records)
#
cat $es_ext_results $es_int_results | grep "0x" >$es_both_results

#--
# Sort by blockNumber and transactionIndex, and we're done
#
# Note: build 'qbsort' with "cd $(QB_ROOT)/src/other/reader ; make ; cd -"
#
qbsort -s $es_both_results >$es_result
