# Deploy basic configuration and directories structure for quickblocks


set(QUICKBLOCKS_HOME "$ENV{HOME}/.quickBlocks")
set(OLD_EXT "old")

file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}" DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)
file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}/configs"   DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)
file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}/slurps"    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)
file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}/abis"      DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)
file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}/makeClass" DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)
file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}/grabABI"   DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)
file(MAKE_DIRECTORY "${QUICKBLOCKS_HOME}/chifra"    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ GROUP_EXECUTE GROUP_READ)

# Do a copy of existing one and install fresh toml file
set(QUICKBLOCKS_TOML_FILE "${QUICKBLOCKS_HOME}/quickBlocks.toml")
if (EXISTS  "${QUICKBLOCKS_TOML_FILE}")
    message (STATUS "WARNING: File ${QUICKBLOCKS_TOML_FILE} exists, renamed to ${QUICKBLOCKS_TOML_FILE}.${OLD_EXT}")
    file(RENAME "${QUICKBLOCKS_TOML_FILE}" "${QUICKBLOCKS_TOML_FILE}.${OLD_EXT}")
endif()

file(COPY "${CMAKE_SOURCE_DIR}/../src/other/install/quickBlocks.toml" DESTINATION "${QUICKBLOCKS_HOME}" FILE_PERMISSIONS OWNER_WRITE OWNER_READ GROUP_READ)
