all:
	@cd libs ; make
	@cd apps ; make
	@cd tools ; make
	@cd monitors ; make

test:
	@cd libs ; make test
	@cd apps ; make test
	@cd tools ; make test
	@cd monitors ; make test

testall:
	@cd libs ; make testall
	@cd apps ; make testall
	@cd tools ; make testall
	@cd monitors ; make testall

clean:
	@cd libs ; make clean
	@cd apps ; make clean
	@cd tools ; make clean
	@cd monitors ; make clean
