#!/usr/bin/env bash

address=$1
name=$2
fin=$3
folder=$3$2
filename=$3$2-$1
monitors=/Users/jrush/src.GitHub/quickBlocks/monitors/
gold=/Users/jrush/src.GitHub/quickBlocks/test/gold/monitors/json

echo "cd $monitors/$folder ; acctExport --fmt json --filter $address| tee x ; cat x | jsonlint | tee $gold/$filename.json ; cd -"
