#!/usr/bin/env bash

address=$1
name=$2
fin=$3
monitors=/Users/jrush/src.GitHub/quickBlocks/monitors/
gold=/Users/jrush/src.GitHub/quickBlocks/test/gold/monitors/json

cd $monitors/$3$2 ; acctExport --fmt json | jsonlint | tee $gold/$3$2-$1.json ; cd -
