name: Test Release
on:
  push:
    tags:
      - 'test-release*' # Only triggers on tags starting with 'test-release'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Fetch All Tags
        run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.18.1'
      - name: Run GoReleaser (Snapshot Mode)
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot # Enable snapshot mode for testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
