# coding: utf-8

"""
    TrueBlocks API

     A REST layer over the TrueBlocks application. With `chifra daemon`, you can run this on your own machine, and make calls to `localhost`. ## How to use this API This API's endpoints are exact translations of the commands used by the chifra CLI application, and the query parameters mirror the commands' options and flags. If you want details, [the commands have their own documentation page](/chifra/introduction/). For detailed descriptions of fields, see [the data model reference](/data-model/intro/).    ### Before you begin  1. [Install the trueblocks-core application](/docs/install/install-core/)   on your machine, change your configs as needed. 2. Run `chifra daemon`     ### Example queries   By default, all calls are to `localhost:8080`.  All options and flags are passed through query parameters.   For example, to get block `100`, make a call to `/blocks` and specify  the block you want in the query parameter:   ```shell  curl \"http://localhost:8080/blocks?blocks=100\"  ```   Some parameters support ranges:   ```shell  curl \"http://localhost:8080/blocks?blocks=100-120\"  ```   Other parameters let you filter your responses. For example, to get only  the unique addresses from that block range:   ```shell  curl \"http://localhost:8080/blocks?blocks=100-110&uniq=true\"  ```   You might want to cache queries on your local machine.   ```shell  \"http://localhost:8080/blocks?blocks=100-110&cache=true\"  ```   Cacheing speeds up repeat queries significantly. The cache options are  particularly useful for calls to data-rich endpoints, like most endpoints  in the  \"Accounts\" collection.   Of course, caches occupy local storage. So cache wisely.   # noqa: E501

    The version of the OpenAPI document: 1.0.0-release
    Contact: info@trueblocks.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class Config(
    schemas.AnyTypeSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    status-related data about the TrueBlocks system including the server and local binary caches
    """


    class MetaOapg:
        
        class properties:
            clientVersion = schemas.AnyTypeSchema
            clientIds = schemas.AnyTypeSchema
            trueblocksVersion = schemas.AnyTypeSchema
            rpcProvider = schemas.AnyTypeSchema
            configPath = schemas.AnyTypeSchema
            cachePath = schemas.AnyTypeSchema
            indexPath = schemas.AnyTypeSchema
            host = schemas.AnyTypeSchema
            isTesting = schemas.AnyTypeSchema
            isApi = schemas.AnyTypeSchema
            isScraping = schemas.AnyTypeSchema
            isArchive = schemas.AnyTypeSchema
            isTracing = schemas.AnyTypeSchema
            hasEskey = schemas.AnyTypeSchema
            hasPinkey = schemas.AnyTypeSchema
            
            
            class ts(
                schemas.AnyTypeSchema,
            ):
            
            
                class MetaOapg:
                    format = 'timestamp'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'ts':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            chains = schemas.AnyTypeSchema
            caches = schemas.AnyTypeSchema
            __annotations__ = {
                "clientVersion": clientVersion,
                "clientIds": clientIds,
                "trueblocksVersion": trueblocksVersion,
                "rpcProvider": rpcProvider,
                "configPath": configPath,
                "cachePath": cachePath,
                "indexPath": indexPath,
                "host": host,
                "isTesting": isTesting,
                "isApi": isApi,
                "isScraping": isScraping,
                "isArchive": isArchive,
                "isTracing": isTracing,
                "hasEskey": hasEskey,
                "hasPinkey": hasPinkey,
                "ts": ts,
                "chains": chains,
                "caches": caches,
            }

    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientVersion"]) -> MetaOapg.properties.clientVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientIds"]) -> MetaOapg.properties.clientIds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trueblocksVersion"]) -> MetaOapg.properties.trueblocksVersion: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rpcProvider"]) -> MetaOapg.properties.rpcProvider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["configPath"]) -> MetaOapg.properties.configPath: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cachePath"]) -> MetaOapg.properties.cachePath: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["indexPath"]) -> MetaOapg.properties.indexPath: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["host"]) -> MetaOapg.properties.host: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isTesting"]) -> MetaOapg.properties.isTesting: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isApi"]) -> MetaOapg.properties.isApi: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isScraping"]) -> MetaOapg.properties.isScraping: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isArchive"]) -> MetaOapg.properties.isArchive: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isTracing"]) -> MetaOapg.properties.isTracing: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hasEskey"]) -> MetaOapg.properties.hasEskey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["hasPinkey"]) -> MetaOapg.properties.hasPinkey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ts"]) -> MetaOapg.properties.ts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chains"]) -> MetaOapg.properties.chains: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caches"]) -> MetaOapg.properties.caches: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["clientVersion", "clientIds", "trueblocksVersion", "rpcProvider", "configPath", "cachePath", "indexPath", "host", "isTesting", "isApi", "isScraping", "isArchive", "isTracing", "hasEskey", "hasPinkey", "ts", "chains", "caches", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientVersion"]) -> typing.Union[MetaOapg.properties.clientVersion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientIds"]) -> typing.Union[MetaOapg.properties.clientIds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trueblocksVersion"]) -> typing.Union[MetaOapg.properties.trueblocksVersion, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rpcProvider"]) -> typing.Union[MetaOapg.properties.rpcProvider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["configPath"]) -> typing.Union[MetaOapg.properties.configPath, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cachePath"]) -> typing.Union[MetaOapg.properties.cachePath, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["indexPath"]) -> typing.Union[MetaOapg.properties.indexPath, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["host"]) -> typing.Union[MetaOapg.properties.host, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isTesting"]) -> typing.Union[MetaOapg.properties.isTesting, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isApi"]) -> typing.Union[MetaOapg.properties.isApi, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isScraping"]) -> typing.Union[MetaOapg.properties.isScraping, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isArchive"]) -> typing.Union[MetaOapg.properties.isArchive, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isTracing"]) -> typing.Union[MetaOapg.properties.isTracing, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hasEskey"]) -> typing.Union[MetaOapg.properties.hasEskey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["hasPinkey"]) -> typing.Union[MetaOapg.properties.hasPinkey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ts"]) -> typing.Union[MetaOapg.properties.ts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chains"]) -> typing.Union[MetaOapg.properties.chains, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caches"]) -> typing.Union[MetaOapg.properties.caches, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["clientVersion", "clientIds", "trueblocksVersion", "rpcProvider", "configPath", "cachePath", "indexPath", "host", "isTesting", "isApi", "isScraping", "isArchive", "isTracing", "hasEskey", "hasPinkey", "ts", "chains", "caches", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        clientVersion: typing.Union[MetaOapg.properties.clientVersion, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        clientIds: typing.Union[MetaOapg.properties.clientIds, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        trueblocksVersion: typing.Union[MetaOapg.properties.trueblocksVersion, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        rpcProvider: typing.Union[MetaOapg.properties.rpcProvider, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        configPath: typing.Union[MetaOapg.properties.configPath, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        cachePath: typing.Union[MetaOapg.properties.cachePath, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        indexPath: typing.Union[MetaOapg.properties.indexPath, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        host: typing.Union[MetaOapg.properties.host, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        isTesting: typing.Union[MetaOapg.properties.isTesting, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        isApi: typing.Union[MetaOapg.properties.isApi, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        isScraping: typing.Union[MetaOapg.properties.isScraping, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        isArchive: typing.Union[MetaOapg.properties.isArchive, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        isTracing: typing.Union[MetaOapg.properties.isTracing, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        hasEskey: typing.Union[MetaOapg.properties.hasEskey, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        hasPinkey: typing.Union[MetaOapg.properties.hasPinkey, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        ts: typing.Union[MetaOapg.properties.ts, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        chains: typing.Union[MetaOapg.properties.chains, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        caches: typing.Union[MetaOapg.properties.caches, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Config':
        return super().__new__(
            cls,
            *_args,
            clientVersion=clientVersion,
            clientIds=clientIds,
            trueblocksVersion=trueblocksVersion,
            rpcProvider=rpcProvider,
            configPath=configPath,
            cachePath=cachePath,
            indexPath=indexPath,
            host=host,
            isTesting=isTesting,
            isApi=isApi,
            isScraping=isScraping,
            isArchive=isArchive,
            isTracing=isTracing,
            hasEskey=hasEskey,
            hasPinkey=hasPinkey,
            ts=ts,
            chains=chains,
            caches=caches,
            _configuration=_configuration,
            **kwargs,
        )
